---
- name: install git
  apt: pkg=git state=present
  tags: dev
- name: configure git
  sudo: yes
  sudo_user: neal
  command: git config --global {{ item }}
  with_items:
    - user.name "Neal Finne"
    - user.email "neal@nealfinne.com"
    - push.default "simple"

- name: create projects directory
  sudo: yes
  sudo_user: neal
  file:
    path: ~/Projects
    state: directory
- name: check out configuration repo
  sudo: yes
  sudo_user: neal
  git:
    repo: https://github.com/nealfinne/configuration.git
    dest: ~/Projects/configuration
    update: no

- name: install jdk
  apt: pkg=default-jdk state=present
  tags: dev java
- name: install gradle
  apt: pkg=gradle state=present
  tags: dev java

- name: install powerline
  apt: pkg=powerline state=present
  tags: dev
- name: set up powerline for neal
  sudo: yes
  sudo_user: neal
  lineinfile:
    line: "{{ item }}"
    dest: ~/.bashrc
  with_items:
    - powerline-daemon -q
    - . /usr/share/powerline/bindings/bash/powerline.sh
- name: configure powerline for neal
  sudo: yes
  sudo_user: neal
  shell: "{{ item }}"
  with_items:
    - "mkdir -p ~/.config/"
    - "[ -e /home/neal/.config/powerline ] || cp -r /usr/share/powerline/config_files/ /home/neal/.config/powerline/"
    - "[ -e /home/neal/.config/powerline/themes/shell/default_leftright.json ] || mv /home/neal/.config/powerline/themes/shell/default.json /home/neal/.config/powerline/themes/shell/default_leftright.json"
    - "[ -e /home/neal/.config/powerline/themes/shell/default.json ] || mv /home/neal/.config/powerline/themes/shell/default_leftonly.json /home/neal/.config/powerline/themes/shell/default.json"
