---
- name: configure git
  sudo: yes
  sudo_user: neal
  ini_file:
    dest: ~/.gitconfig
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    -
      section: user
      option: name
      value: Neal Finne
    -
      section: user
      option: email
      value: neal@nealfinne.com
    -
      section: push
      option: default
      value: simple

- name: create .ssh directory
  sudo: yes
  sudo_user: neal
  file:
    path: ~/.ssh
    state: directory
    mode: 0700
- name: copy ssh private key
  sudo: yes
  sudo_user: neal
  copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/id_rsa
    mode: 0600
  when: copy_ssh_private_key
- name: create projects directory
  sudo: yes
  sudo_user: neal
  file:
    path: ~/Projects
    state: directory
- name: add github.com to known_hosts
  sudo: yes
  sudo_user: neal
  lineinfile:
    dest: ~/.ssh/known_hosts
    line: "|1|L0/xKEbyVnnBqbUn+9ydO8CqHS0=|9B4WzQG2tatZLw9Yt9R2vXcMbS4= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
    create: yes
    mode: 0600
- name: check out configuration repo using ssh
  sudo: yes
  sudo_user: neal
  git:
    repo: git@github.com:nealfinne/configuration.git
    dest: ~/Projects/configuration
    update: no
  when: copy_ssh_private_key
- name: check out configuration repo using https
  sudo: yes
  sudo_user: neal
  git:
    repo: https://github.com/nealfinne/configuration.git
    dest: ~/Projects/configuration
    update: no
  when: not copy_ssh_private_key

- name: install powerline (Debian)
  apt: pkg=powerline state=present
  when: ansible_distribution == 'Debian'
- name: install powerline (Ubuntu)
  pip: name=powerline-status state=present
  when: ansible_distribution == 'Ubuntu'
- name: set up powerline for neal (Debian)
  sudo: yes
  sudo_user: neal
  lineinfile:
    line: "{{ item }}"
    dest: ~/.bashrc
  with_items:
    - powerline-daemon -q
    - . /usr/share/powerline/bindings/bash/powerline.sh
  when: ansible_distribution == 'Debian'
- name: set up powerline for neal (Ubuntu)
  sudo: yes
  sudo_user: neal
  lineinfile:
    line: "{{ item }}"
    dest: ~/.bashrc
  with_items:
    - powerline-daemon -q
    - . /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh
  when: ansible_distribution == 'Ubuntu'
