---
- name: configure git
  sudo: yes
  sudo_user: neal
  ini_file:
    dest: ~/.gitconfig
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    -
      section: user
      option: name
      value: Neal Finne
    -
      section: user
      option: email
      value: neal@nealfinne.com
    -
      section: push
      option: default
      value: simple

- name: create projects directory
  sudo: yes
  sudo_user: neal
  file:
    path: ~/Projects
    state: directory
- name: check out configuration repo
  sudo: yes
  sudo_user: neal
  git:
    repo: https://github.com/nealfinne/configuration.git
    dest: ~/Projects/configuration
    update: no

- name: install powerline
  apt: pkg=powerline state=present
  when: ansible_distribution == 'Debian'
- name: set up powerline for neal
  sudo: yes
  sudo_user: neal
  lineinfile:
    line: "{{ item }}"
    dest: ~/.bashrc
  with_items:
    - powerline-daemon -q
    - . /usr/share/powerline/bindings/bash/powerline.sh
  when: ansible_distribution == 'Debian'
