---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: provision a master instance
      ec2:
        key_name: neal
        region: us-west-2
        image: ami-3d56520d
        instance_type: t2.nano
        count_tag:
          Name: master
        exact_count: 1
        instance_tags:
          Name: master
        group: master
      register: ec2
    - name: add all public instance ip addresses to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.tagged_instances
- hosts: ec2hosts
  user: admin
  sudo: yes
  roles:
    - common
    - master
